from magic_crawler.extract_text_from_url_crawler_pro import extract_text_from_url_crawler_pro
from magic_crawler.extract_text_from_url_crawler_jina import extract_text_from_url_crawler_jina
from magic_crawler.extract_text_from_url_crawler_local import extract_text_from_url_crawler_local

__version__ = '0.0.6'
